import { ROUTINE, capitalize, dateKey, exerciseById, formatWeight, isTrainingDay, nearestLoadable, plateLoad, recommendation, scheduledDay, setsFor, targetFor } from './routine.js';

const app = document.querySelector('#app');
const sheetRoot = document.querySelector('#sheet-root');
const DB_NAME = 'plates-workouts';
const DB_VERSION = 1;
let workouts = [];
let view = 'today';
let month = new Date();
let activeDate = dateKey(new Date());
let selectedExercise = 'bench';
let importPayload = null;
let draft = null;

const escape = (value = '') => String(value).replace(/[&<>'"]/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[character]);
const localDate = (key) => new Date(`${key}T12:00:00`);
const prettyDate = (key, short = false) => localDate(key).toLocaleDateString(undefined, short ? { month:'short', day:'numeric' } : { weekday:'long', month:'long', day:'numeric' });
const id = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;

function openDatabase() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains('workouts')) db.createObjectStore('workouts', { keyPath:'id' }); };
    request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error);
  });
}
async function loadWorkouts() { const db = await openDatabase(); workouts = await new Promise((resolve, reject) => { const req = db.transaction('workouts').objectStore('workouts').getAll(); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); workouts.sort((a,b) => a.date.localeCompare(b.date)); }
async function saveWorkout(workout) { const db = await openDatabase(); await new Promise((resolve, reject) => { const req = db.transaction('workouts', 'readwrite').objectStore('workouts').put(workout); req.onsuccess = resolve; req.onerror = () => reject(req.error); }); const index = workouts.findIndex(item => item.id === workout.id); if (index < 0) workouts.push(workout); else workouts[index] = workout; workouts.sort((a,b) => a.date.localeCompare(b.date)); }
async function replaceAll(next) { const db = await openDatabase(); await new Promise((resolve, reject) => { const tx = db.transaction('workouts', 'readwrite'); tx.objectStore('workouts').clear(); next.forEach(item => tx.objectStore('workouts').put(item)); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); workouts = next.sort((a,b) => a.date.localeCompare(b.date)); }

function dayWorkout(date) { return workouts.find(workout => workout.date === date); }
function freshWorkout(date, day) {
  return { id:id(), date, day, notes:'', createdAt:new Date().toISOString(), lifts:Object.fromEntries(ROUTINE.days[day].map(exercise => [exercise.exercise, { weightLb:recommendation(exercise.exercise, workouts).weight, reps:Array(setsFor(exercise.scheme)).fill(null), status:'pending', note:'' }])) };
}
function nav() { return `<nav class="bottom-nav"><button class="tab ${view === 'today' ? 'active':''}" data-action="view" data-view="today"><span class="nav-icon">◉</span>Workout</button><button class="tab ${view === 'calendar' ? 'active':''}" data-action="view" data-view="calendar"><span class="nav-icon">▦</span>Calendar</button><button class="tab ${view === 'progress' ? 'active':''}" data-action="view" data-view="progress"><span class="nav-icon">⌁</span>Progress</button></nav>`; }
function topbar() { return `<div class="topbar"><div class="wordmark"><i class="mark"></i>Plates</div><button class="icon-button" aria-label="Backup and import" data-action="tools">⋯</button></div>`; }

function plateMarkup(weight) {
  const load = plateLoad(weight);
  if (!load.exact) return `<div class="plate-rack"><div class="plate-note load-warning">Not loadable with these plates. <button class="small-btn" data-action="nearest" data-weight="${weight}">Use ${formatWeight(nearestLoadable(weight))}</button></div></div>`;
  const colors = {45:'#e85b49',35:'#4775a8',25:'#f6b85e',10:'#40816e',5:'#253247',2.5:'#253247',1.25:'#253247'};
  const sizes = {45:40,35:37,25:34,10:28,5:23,2.5:19,1.25:16};
  return `<div class="plate-rack"><div class="plates"><span class="bar"></span>${load.plates.map(plate => `<span class="plate" style="--plate:${colors[plate]};--size:${sizes[plate]}px">${plate}</span>`).join('') || '<span class="plate-note">bar only</span>'}</div><div class="plate-note">${formatWeight(load.perSide)} each side · 45 lb bar</div></div>`;
}
function liftMarkup(exercise, lift, readonly = false) {
  const sets = setsFor(exercise.scheme); const target = targetFor(exercise.scheme); const recommended = recommendation(exercise.exercise, workouts);
  const reps = lift.reps || [];
  if (readonly) return `<article class="lift ${lift.status === 'skipped' ? 'skipped':''}"><div class="lift-top"><div><h2>${escape(exercise.name)}</h2><p class="scheme">${exercise.scheme}</p></div><strong>${formatWeight(lift.weightLb)}${exercise.kind === 'dumbbell' ? ' each' : ''}</strong></div>${exercise.kind === 'barbell' ? plateMarkup(lift.weightLb) : ''}<p class="reps-readout">${reps.length ? `Sets: ${reps.map(rep => rep ?? '—').join(' · ')}` : lift.legacyRepNote ? `Legacy note: ${lift.legacyRepNote} reps` : 'No set-by-set reps recorded'}</p><p class="status-readout">${lift.status || 'unknown'}${lift.substitute ? ` · substituted with ${escape(lift.substitute.exercise)} at ${formatWeight(lift.substitute.weightLb)}` : ''}</p>${lift.note ? `<p class="history-note">${escape(lift.note)}</p>` : ''}</article>`;
  return `<article class="lift ${lift.status === 'skipped' ? 'skipped':''}" data-exercise="${exercise.exercise}"><div class="lift-top"><div><h2>${escape(exercise.name)}</h2><p class="scheme">${exercise.scheme}</p></div><span class="weight-type">${exercise.kind === 'dumbbell' ? 'per dumbbell' : 'working weight'}</span></div><p class="recommendation"><strong>Suggested ${formatWeight(recommended.weight)}</strong> · ${recommended.reason}</p><div class="weight-row"><div class="weight-control"><button aria-label="Decrease weight" data-action="weight" data-delta="-${exercise.kind === 'barbell' ? 2.5 : 1.25}">−</button><input aria-label="${escape(exercise.name)} weight" data-action="weight-input" inputmode="decimal" step="1.25" type="number" value="${lift.weightLb}"><span class="unit">lb</span><button aria-label="Increase weight" data-action="weight" data-delta="${exercise.kind === 'barbell' ? 2.5 : 1.25}">+</button></div></div>${exercise.kind === 'barbell' ? plateMarkup(lift.weightLb) : ''}<div class="sets">${Array.from({length:sets}, (_, index) => `<div class="set-row"><span class="set-label">Set ${index + 1}</span><div class="rep-control"><button data-action="rep" data-set="${index}" data-delta="-1">−</button><span class="rep-value">${reps[index] ?? '—'}</span><button data-action="rep" data-set="${index}" data-delta="1">+</button></div><button class="set-hit ${reps[index] === target ? 'done':''}" data-action="hit-set" data-set="${index}">${reps[index] === target ? 'Done' : `${target} reps`}</button></div>`).join('')}</div><div class="statuses"><button class="status ${lift.status === 'done' ? 'active':''}" data-action="status" data-status="done">Done</button><button class="status ${lift.status === 'failed' ? 'active':''}" data-action="status" data-status="failed">Failed</button><button class="status ${lift.status === 'skipped' ? 'active':''}" data-action="status" data-status="skipped">Skipped</button></div><textarea class="lift-note" data-action="lift-note" placeholder="Optional note">${escape(lift.note || '')}</textarea></article>`;
}
function draftFor(date) {
  if (draft?.date === date) return draft;
  const saved = dayWorkout(date);
  draft = saved ? structuredClone(saved) : freshWorkout(date, scheduledDay(date, workouts));
  return draft;
}
function workoutView() {
  const today = dateKey(new Date());
  if (!isTrainingDay(today)) return restView(today);
  const date = activeDate === today ? today : activeDate;
  const workout = draftFor(date);
  const saved = !!dayWorkout(date); const day = ROUTINE.days[workout.day];
  return `${topbar()}<div class="workout-heading"><div><p class="eyebrow">${saved ? 'Workout log' : 'Today’s training'}</p><h1>${workout.day}</h1></div><time>${prettyDate(date)}</time></div>${workouts.length === 0 ? `<div class="callout"><strong>Your old notes are ready.</strong><p>Assign dates once and they’ll become normal calendar history.</p><button class="primary" data-action="legacy">Add supplied history</button></div>` : ''}<section class="workout" data-date="${date}">${day.map(exercise => liftMarkup(exercise, workout.lifts[exercise.exercise])).join('')}<textarea class="lift-note" data-action="workout-note" placeholder="Workout notes">${escape(workout.notes || '')}</textarea><div class="save-row"><button class="primary" data-action="save">${saved ? 'Save changes' : 'Save workout'}</button><span class="saved">${saved ? 'Saved locally' : 'Nothing is sent anywhere'}</span></div></section>${nav()}`;
}
function restView(today) { let next = new Date(`${today}T12:00:00`); do { next.setDate(next.getDate() + 1); } while (!isTrainingDay(next)); const nextDate = dateKey(next); const day = scheduledDay(nextDate, workouts); return `${topbar()}<div class="workout-heading"><div><p class="eyebrow">Rest day</p><h1>Weekend</h1></div><time>${prettyDate(today)}</time></div><div class="callout"><strong>Next up: ${capitalize(day)}</strong><p>${prettyDate(nextDate, true)} · the cycle pauses for the weekend, then carries on.</p><button class="primary" data-action="open-next" data-date="${nextDate}">Preview ${capitalize(day)}</button></div>${nav()}`; }
function calendarView() { const year = month.getFullYear(), monthNumber = month.getMonth(); const first = new Date(year, monthNumber, 1); const leading = (first.getDay() + 6) % 7; const days = new Date(year, monthNumber + 1, 0).getDate(); const today = dateKey(new Date()); const cells = Array(leading).fill('<span></span>'); for (let n = 1; n <= days; n++) { const key = dateKey(new Date(year, monthNumber, n, 12)); const has = !!dayWorkout(key); cells.push(`<button class="day ${has ? 'has-workout':''} ${key === today ? 'current':''}" ${has ? `data-action="open-date" data-date="${key}"` : ''}>${n}${has ? '<i class="dot"></i>' : ''}</button>`); } const entries = workouts.filter(workout => workout.date?.startsWith(`${year}-${String(monthNumber + 1).padStart(2,'0')}`)); return `${topbar()}<div class="section-head"><div><p class="eyebrow">History</p><h1>Calendar</h1></div></div><div class="month-head"><button class="icon-button" data-action="month" data-delta="-1" aria-label="Previous month">‹</button><strong>${month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button class="icon-button" data-action="month" data-delta="1" aria-label="Next month">›</button></div><div class="calendar">${['M','T','W','T','F','S','S'].map(d => `<span class="weekday">${d}</span>`).join('')}${cells.join('')}</div><p class="calendar-help">A dot marks a tracked workout. Tap it to reopen the full log.</p><section class="history"><h2>This month</h2>${entries.length ? entries.map(workout => `<button class="history-item" data-action="open-date" data-date="${workout.date}"><strong>${capitalize(workout.day)}</strong><span>${prettyDate(workout.date, true)} →</span></button>`).join('') : '<p class="empty">No workouts in this month.</p>'}</section>${nav()}`; }
function progressView() { const exercises = Object.values(ROUTINE.days).flat(); const points = workouts.flatMap(workout => Object.entries(workout.lifts || {}).map(([exercise,lift]) => ({workout, exercise, lift}))).filter(point => point.exercise === selectedExercise && ['done','failed'].includes(point.lift.status) && Number.isFinite(point.lift.weightLb)); const labels = exercises.map(exercise => `<option value="${exercise.exercise}" ${exercise.exercise === selectedExercise ? 'selected':''}>${exercise.name}</option>`).join(''); return `${topbar()}<div class="section-head"><div><p class="eyebrow">Working weight</p><h1>Progress</h1></div></div><select class="select" data-action="select-exercise">${labels}</select>${chart(points)}<p class="calendar-help">Tap a point to open its workout. Red points indicate a failed lift; skips are not charted.</p>${nav()}`; }
function chart(points) { if (!points.length) return '<div class="empty">No dated working sets for this lift yet.</div>'; const width=340, height=250, pad={l:40,r:16,t:20,b:34}; const values=points.map(point=>point.lift.weightLb); const min=Math.min(...values), max=Math.max(...values); const y = value => pad.t + (max === min ? 0.5 : (max-value)/(max-min))*(height-pad.t-pad.b); const x = index => pad.l + (points.length === 1 ? (width-pad.l-pad.r)/2 : index/(points.length-1)*(width-pad.l-pad.r)); const path=points.map((point,index)=>`${index?'L':'M'}${x(index)} ${y(point.lift.weightLb)}`).join(' '); return `<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Working weight over time"><line x1="${pad.l}" x2="${pad.l}" y1="${pad.t}" y2="${height-pad.b}" stroke="#e9dfcf"/><line x1="${pad.l}" x2="${width-pad.r}" y1="${height-pad.b}" y2="${height-pad.b}" stroke="#e9dfcf"/><text x="5" y="${pad.t+4}">${formatWeight(max)}</text><text x="5" y="${height-pad.b}">${formatWeight(min)}</text><path class="line" d="${path}"/>${points.map((point,index)=>`<circle class="point ${point.lift.status === 'failed' ? 'failed':''}" data-action="chart-point" data-date="${point.workout.date}" cx="${x(index)}" cy="${y(point.lift.weightLb)}" r="6"/><text x="${x(index)}" y="${height-10}" text-anchor="middle">${prettyDate(point.workout.date,true)}</text>`).join('')}</svg>`; }
function detailsView(workout) { return `${topbar()}<button class="small-btn" data-action="back-calendar">← Calendar</button><div class="workout-heading"><div><p class="eyebrow">Saved workout</p><h1>${workout.day}</h1></div><time>${prettyDate(workout.date)}</time></div><section class="details">${Object.entries(workout.lifts).map(([key,lift]) => { const exercise = exerciseById(key) || {name:key,scheme:lift.scheme,kind:'machine'}; return liftMarkup(exercise, lift, true); }).join('')}${workout.notes ? `<div class="callout"><strong>Workout notes</strong><p>${escape(workout.notes)}</p></div>` : ''}</section>${nav()}`; }
function render() { const selected = view === 'calendar' ? calendarView() : view === 'progress' ? progressView() : view === 'details' ? detailsView(dayWorkout(activeDate)) : workoutView(); app.innerHTML = selected; }

function currentDraft() { return draftFor(document.querySelector('.workout')?.dataset.date); }
function syncDraftFromDom() { if (!document.querySelector('.workout')) return; const workout=currentDraft(); workout.notes = document.querySelector('[data-action="workout-note"]')?.value || ''; document.querySelectorAll('.lift[data-exercise]').forEach(card => { const lift=workout.lifts[card.dataset.exercise]; lift.note=card.querySelector('[data-action="lift-note"]')?.value || ''; const input=card.querySelector('[data-action="weight-input"]'); if (input) lift.weightLb=Math.round(Number(input.value || lift.weightLb)*100)/100; }); }
function updateLift(event, change) { const card=event.target.closest('.lift'); if (!card) return; syncDraftFromDom(); const workout=currentDraft(), lift=workout.lifts[card.dataset.exercise]; change(lift); render(); }
function updateDraftWeightFromInput(input) { const card = input.closest('.lift'); const weight = Number(input.value); if (!card || !Number.isFinite(weight) || weight < 0) return; const workout = currentDraft(); workout.lifts[card.dataset.exercise].weightLb = Math.round(weight * 100) / 100; }
async function commitDraft() { syncDraftFromDom(); const workout=currentDraft(); await saveWorkout(workout); draft=structuredClone(workout); toast('Saved on this device'); render(); }

function toast(message) { const element=document.createElement('div'); element.className='toast'; element.textContent=message; document.body.append(element); setTimeout(()=>element.remove(),1800); }
function showSheet(content) { sheetRoot.innerHTML=`<div class="sheet-backdrop" data-action="close-sheet"><section class="sheet">${content}</section></div>`; }
function toolsSheet() { showSheet(`<h2>Data stays on this phone</h2><p>Back up or restore your private workout history.</p><div class="sheet-actions"><button class="primary" data-action="export">Export JSON</button><button class="secondary" data-action="choose-import">Import JSON</button><button class="secondary" data-action="legacy">Add supplied history</button></div><input class="file-input" id="import-file" type="file" accept="application/json,.json"><div class="sheet-actions"><button class="secondary" data-action="close-sheet">Close</button></div>`); }
function previousTrainingDate(date) { const copy=new Date(`${date}T12:00:00`); do { copy.setDate(copy.getDate()-1); } while (!isTrainingDay(copy)); return dateKey(copy); }
function mappingSheet(payload) { importPayload=payload; const all=payload.workouts; const newest=all.at(-1); const suggested=dateKey(new Date()); showSheet(`<h2>Assign the old workout dates</h2><p>Your iPhone note has order but no dates. Choose the date for its newest workout; nothing is saved until you review the mapping.</p><label for="anchor">Newest ${capitalize(newest.day)} workout</label><input id="anchor" type="date" value="${suggested}"><div class="sheet-actions"><button class="primary" data-action="propose-dates">Review dates</button><button class="secondary" data-action="close-sheet">Cancel</button></div>`); }
function buildMapping(anchor) { let date=anchor; const result=[]; for (let index=importPayload.workouts.length-1; index>=0;index--) { result[index]=date; date=previousTrainingDate(date); } return result; }
function reviewMapping() { const anchor=document.querySelector('#anchor').value; if (!anchor || !isTrainingDay(anchor)) return toast('Choose a Monday–Friday anchor date'); const dates=buildMapping(anchor); showSheet(`<h2>Review date mapping</h2><p>Edit any date before importing. The original sequence and notes are preserved.</p><div class="mapping">${importPayload.workouts.map((workout,index)=>`<label class="map-row"><span>#${workout.sequence || index+1} · ${capitalize(workout.day)}</span><input type="date" data-map="${index}" value="${dates[index]}"></label>`).join('')}</div><div class="sheet-actions"><button class="primary" data-action="save-mapped" data-mode="merge">Import & merge</button><button class="secondary danger" data-action="save-mapped" data-mode="replace">Replace all</button><button class="secondary" data-action="close-sheet">Cancel</button></div>`); }
function normalizeImport(payload, dates) { return payload.workouts.map((workout,index) => ({...workout, id:workout.id || id(), date:dates?.[index] || workout.date, importedAt:new Date().toISOString()})); }
async function importWithDates(mode) { const dates=[...document.querySelectorAll('[data-map]')].map(input=>input.value); if (dates.some(date=>!date)) return toast('Every workout needs a date'); const incoming=normalizeImport(importPayload,dates); if (mode === 'replace') { if (!confirm('Replace every workout currently stored on this phone?')) return; await replaceAll(incoming); } else { const byDate=new Map(workouts.map(workout=>[workout.date,workout])); incoming.forEach(workout=>byDate.set(workout.date,workout)); await replaceAll([...byDate.values()]); } sheetRoot.innerHTML=''; view='calendar'; month=localDate(dates.at(-1)); toast(`${incoming.length} workouts imported`); render(); }
async function receiveImport(payload) { if (!payload?.workouts || !Array.isArray(payload.workouts)) return toast('That JSON does not contain workouts'); if (payload.workouts.some(workout=>!workout.date)) return mappingSheet(payload); importPayload=payload; showSheet(`<h2>Ready to import</h2><p>${payload.workouts.length} dated workouts found. Merge keeps unrelated dates; replacement erases the current local history.</p><div class="sheet-actions"><button class="primary" data-action="import-dated" data-mode="merge">Import & merge</button><button class="secondary danger" data-action="import-dated" data-mode="replace">Replace all</button><button class="secondary" data-action="close-sheet">Cancel</button></div>`); }
async function importDated(mode) { const incoming=normalizeImport(importPayload); if (mode === 'replace') { if (!confirm('Replace every workout currently stored on this phone?')) return; await replaceAll(incoming); } else { const byDate=new Map(workouts.map(workout=>[workout.date,workout])); incoming.forEach(workout=>byDate.set(workout.date,workout)); await replaceAll([...byDate.values()]); } sheetRoot.innerHTML=''; toast(`${incoming.length} workouts imported`); render(); }
function exportData() { const payload={schemaVersion:2,units:'lb',routineId:ROUTINE.id,exportedAt:new Date().toISOString(),workouts}; const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})); const anchor=document.createElement('a'); anchor.href=url; anchor.download=`plates-backup-${dateKey(new Date())}.json`; anchor.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); toast('Backup downloaded'); }

document.addEventListener('click', async event => { const target=event.target.closest('[data-action]'); if (!target) return; const action=target.dataset.action;
  if (action==='view') { syncDraftFromDom(); view=target.dataset.view; render(); }
  if (action==='tools') toolsSheet(); if (action==='close-sheet') sheetRoot.innerHTML='';
  if (action==='open-next') { activeDate=target.dataset.date; draft=null; view='today'; render(); }
  if (action==='open-date' || action==='chart-point') { activeDate=target.dataset.date; draft=null; view='details'; render(); }
  if (action==='back-calendar') { view='calendar'; render(); }
  if (action==='month') { month.setMonth(month.getMonth()+Number(target.dataset.delta)); render(); }
  if (action==='weight') updateLift(event,lift => lift.weightLb=Math.max(0,Math.round((Number(lift.weightLb)+Number(target.dataset.delta))*100)/100));
  if (action==='nearest') updateLift(event,lift=>lift.weightLb=nearestLoadable(Number(target.dataset.weight)));
  if (action==='rep') updateLift(event,lift=>{ const index=Number(target.dataset.set); const now=lift.reps[index] ?? 0; lift.reps[index]=Math.max(0,now+Number(target.dataset.delta)); });
  if (action==='hit-set') updateLift(event,lift=>{ const index=Number(target.dataset.set); const targetReps=targetFor(exerciseById(event.target.closest('.lift').dataset.exercise).scheme); lift.reps[index]=lift.reps[index]===targetReps ? null : targetReps; if (lift.reps.every(rep=>rep>=targetReps)) lift.status='done'; });
  if (action==='status') updateLift(event,lift=>lift.status=target.dataset.status);
  if (action==='save') await commitDraft();
  if (action==='export') exportData();
  if (action==='choose-import') document.querySelector('#import-file').click();
  if (action==='legacy') { const payload=await fetch('./legacy-history.json').then(response=>response.json()); mappingSheet(payload); }
  if (action==='propose-dates') reviewMapping(); if (action==='save-mapped') await importWithDates(target.dataset.mode); if (action==='import-dated') await importDated(target.dataset.mode);
});
document.addEventListener('change', async event => { if (event.target.dataset.action==='weight-input') updateDraftWeightFromInput(event.target); if (event.target.dataset.action==='select-exercise') { selectedExercise=event.target.value; render(); } if (event.target.id==='import-file' && event.target.files[0]) { try { await receiveImport(JSON.parse(await event.target.files[0].text())); } catch { toast('Could not read that JSON file'); } } });
document.addEventListener('input', event => { if (event.target.dataset.action==='weight-input') updateDraftWeightFromInput(event.target); if (event.target.dataset.action==='lift-note' || event.target.dataset.action==='workout-note') { /* retained until Save, intentionally no background writes */ } });

await loadWorkouts();
render();
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
